import { LoginProvider } from "./login-provider"
import { Header} from '@moon-app/components/src/header/header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <LoginProvider>
          <Header />
        </LoginProvider>
      </body>
    </html>
  )
}
